services:

  #  Minecraft Server Integration in development.
  # minecraft-server:
  #   container_name: "minecraft-server"
  #   image: "openjdk:${OPENJDK_VERSION}"
  #   ports:
  #     - "25565:25565"  # Minecraft default server port
  #     - "25575:25575"  # Minecraft default rcon port 
  #   environment:
  #     EULA: "true"
  #     RAM: "${DEDICATED_RAM}"
  #   volumes:
  #     - ./minecraft-data:/data
  #     - ./java:/java
  #   working_dir: /data
  #   tty: true
  #   command: ["sh", "-c", "java ${RAM_MAX} ${RAM_MIN} -jar ../java/${JAR_SERVER_FILE} nogui"]

  web-server:
    container_name: 'web-server'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    volumes:
      - ./web:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./minecraft-data:/var/www/html/minecraft-data/
      - './config/apache/apache2.conf:/etc/apache2/apache2.conf'
      - './config/apache/certs/:/etc/apache2/certs/'
      - './config/apache/ports.conf:/etc/apache2/ports.conf'
      - './config/apache/sites-available/:/etc/apache2/sites-available/'
      - './config/apache/mods-available/:/etc/apache2/mods-available/'
    working_dir: /var/www/html
    
